[theme]
base = "light"  # Use "light" or "dark" for base theme
primaryColor = "#4CAF50"  # Green primary color for buttons and highlights
backgroundColor = "#f5f5f5"  # Light gray background color
secondaryBackgroundColor = "#ffffff"  # White sidebar background
textColor = "#333333"  # Dark text color
font = "sans serif"  # Optional: Customize the font
